# 端口
server:
  port: 8888
  servlet:
    context-path: /

# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/static/,classpath:/templates/

  devtools: # 热部署
    livereload:
      enabled: true
  jackson: # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.yx.pojo
  mapper-locations: classpath:/com/yx/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志(默认)

